### PR TITLE
Update reqwest version

### PR DESCRIPTION
**Pull request by jianshu93**
Update to newest version of reqwest to address compiling error on MacOS.

### CODE REVIEW

**Review by eric9n — COMMENTED** [review]
Thank you for your contribution to the Kun_peng repository. I truly appreciate the effort you put into creating the pull request. However, I have a few concerns that I wanted to share with you.

The charts you provided appear to be post-processed results rather than direct outputs from Kun_peng, which makes it difficult to evaluate their relevance fully. Additionally, the context for the charts is unclear, and it's not evident where the data comes from. If the intention is to include these charts as reference documentation for users, it might be helpful to accompany them with a more detailed data analysis workflow, serving as a demo of how Kun_peng can be used to analyze data.

**Comment by eric9n** [comment]
This Python code performs downstream analysis of Kun_peng results and is not closely related to Kun_peng itself, correct?

**Comment by jianshu93** [comment]
I can remove it but add kraken2tools there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jianshu93** [comment]
How about this time?

I have some thoughts on what journal to go for kun_peng and what could be the key highlights compared to kraken2 since a Rust implementation itself with memory improvement is not enough for a good and impactful paper.

Thanks,

Jianshu

**Comment by jianshu93** [comment]
Or I can remove the html files, which are so large, but it provides interactive results, which is more helpful to understand the detailed difference between two tools. 

Jianshu

**Comment by jianshu93** [comment]
Please review and let me know your thoughts.

Thanks,

Jianshu

**Comment by eric9n** [comment]
Thank you. Frankly, I don't think this change adds much value to the codebase.

**Pull request closed without merging**
